# Generated by Django 4.2 on 2026-04-05 14:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Số lượng')),
                ('price', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=15, null=True, verbose_name='Đơn giá (đ)')),
                ('sub_total', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=15, null=True, verbose_name='Tạm tính (đ)')),
                ('shipping', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=15, null=True, verbose_name='Phí vận chuyển (đ)')),
                ('tax', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=15, null=True, verbose_name='Thuế VAT (đ)')),
                ('total', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=15, null=True, verbose_name='Tổng cộng (đ)')),
                ('size', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kích cỡ')),
                ('color', models.CharField(blank=True, max_length=100, null=True, verbose_name='Màu sắc')),
                ('cart_id', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Mã giỏ hàng')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày thêm')),
            ],
            options={
                'verbose_name': 'Giỏ hàng',
                'verbose_name_plural': 'Giỏ hàng',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Tên danh mục')),
                ('image', models.ImageField(blank=True, default='category.jpg', null=True, upload_to='images', verbose_name='Hình ảnh')),
                ('slug', models.SlugField(unique=True, verbose_name='Đường dẫn')),
            ],
            options={
                'verbose_name': 'Danh mục',
                'verbose_name_plural': 'Danh mục sản phẩm',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='Mã giảm giá')),
                ('discount', models.IntegerField(default=1, verbose_name='Mức giảm (%)')),
            ],
            options={
                'verbose_name': 'Mã giảm giá',
                'verbose_name_plural': 'Mã giảm giá',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(default='gallery.jpg', upload_to='images', verbose_name='Hình ảnh')),
                ('gallery_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=6, max_length=10, prefix='', verbose_name='Mã ảnh')),
            ],
            options={
                'verbose_name': 'Ảnh sản phẩm',
                'verbose_name_plural': 'Thư viện ảnh sản phẩm',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_total', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Tạm tính (đ)')),
                ('shipping', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Phí vận chuyển (đ)')),
                ('tax', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Thuế VAT (đ)')),
                ('service_fee', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Phí dịch vụ (đ)')),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Tổng cộng (đ)')),
                ('payment_status', models.CharField(choices=[('Paid', 'Đã thanh toán'), ('Processing', 'Đang xử lý'), ('Failed', 'Thất bại')], default='Processing', max_length=100, verbose_name='Trạng thái thanh toán')),
                ('payment_method', models.CharField(blank=True, choices=[('COD', 'Thanh toán khi nhận hàng (COD)'), ('VNPay', 'VNPay'), ('VietQR', 'Quét mã QR')], default=None, max_length=100, null=True, verbose_name='Phương thức thanh toán')),
                ('order_status', models.CharField(choices=[('Pending', 'Chờ xử lý'), ('Processing', 'Đang xử lý'), ('Shipped', 'Đang giao hàng'), ('Fulfilled', 'Đã giao hàng'), ('Cancelled', 'Đã hủy')], default='Pending', max_length=100, verbose_name='Trạng thái đơn hàng')),
                ('initial_total', models.DecimalField(decimal_places=0, default=0, help_text='Tổng tiền gốc trước khi áp dụng giảm giá', max_digits=15, verbose_name='Tổng tiền gốc (đ)')),
                ('saved', models.DecimalField(blank=True, decimal_places=0, default=0, help_text='Số tiền khách hàng được giảm', max_digits=15, null=True, verbose_name='Tiết kiệm được (đ)')),
                ('order_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=6, max_length=25, prefix='', verbose_name='Mã đơn hàng')),
                ('payment_id', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Mã giao dịch')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày đặt hàng')),
            ],
            options={
                'verbose_name': 'Đơn hàng',
                'verbose_name_plural': 'Đơn hàng',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(choices=[('Pending', 'Chờ xử lý'), ('Processing', 'Đang xử lý'), ('Shipped', 'Đang giao hàng'), ('Fulfilled', 'Đã giao hàng'), ('Cancelled', 'Đã hủy')], default='Pending', max_length=100, verbose_name='Trạng thái đơn hàng')),
                ('shipping_service', models.CharField(blank=True, choices=[('GHN', 'Giao Hàng Nhanh (GHN)'), ('ViettelPost', 'Viettel Post')], default=None, max_length=100, null=True, verbose_name='Đơn vị vận chuyển')),
                ('tracking_id', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Mã vận đơn')),
                ('qty', models.IntegerField(default=0, verbose_name='Số lượng')),
                ('color', models.CharField(blank=True, max_length=100, null=True, verbose_name='Màu sắc')),
                ('size', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kích cỡ')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Đơn giá (đ)')),
                ('sub_total', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Tạm tính (đ)')),
                ('shipping', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Phí vận chuyển (đ)')),
                ('tax', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Thuế VAT (đ)')),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Tổng cộng (đ)')),
                ('initial_total', models.DecimalField(decimal_places=0, default=0, help_text='Tổng tiền gốc trước khi áp dụng giảm giá', max_digits=15, verbose_name='Tổng tiền gốc (đ)')),
                ('saved', models.DecimalField(blank=True, decimal_places=0, default=0, help_text='Số tiền khách hàng được giảm', max_digits=15, null=True, verbose_name='Tiết kiệm được (đ)')),
                ('applied_coupon', models.BooleanField(default=False, verbose_name='Đã áp dụng mã giảm giá')),
                ('item_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=6, max_length=25, prefix='', verbose_name='Mã sản phẩm')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày đặt')),
            ],
            options={
                'verbose_name': 'Chi tiết đơn hàng',
                'verbose_name_plural': 'Chi tiết đơn hàng',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên sản phẩm')),
                ('image', models.FileField(blank=True, default='product.jpg', null=True, upload_to='images', verbose_name='Ảnh đại diện')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('price', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=15, null=True, verbose_name='Giá bán (đ)')),
                ('regular_price', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=15, null=True, verbose_name='Giá gốc (đ)')),
                ('stock', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Số lượng tồn kho')),
                ('shipping', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=15, null=True, verbose_name='Phí vận chuyển (đ)')),
                ('status', models.CharField(choices=[('Published', 'Đang bán'), ('Draft', 'Bản nháp'), ('Disabled', 'Đã ẩn')], default='Published', max_length=50, verbose_name='Trạng thái')),
                ('featured', models.BooleanField(default=False, verbose_name='Nổi bật trên Marketplace')),
                ('sku', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=5, max_length=50, prefix='SKU', unique=True, verbose_name='Mã SKU')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='Đường dẫn')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày đăng')),
            ],
            options={
                'verbose_name': 'Sản phẩm',
                'verbose_name_plural': 'Sản phẩm',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Tên biến thể')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Biến thể',
                'verbose_name_plural': 'Biến thể sản phẩm',
            },
        ),
        migrations.CreateModel(
            name='VariantItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Tên thuộc tính')),
                ('content', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Giá trị thuộc tính')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_items', to='store.variant', verbose_name='Biến thể')),
            ],
            options={
                'verbose_name': 'Chi tiết biến thể',
                'verbose_name_plural': 'Chi tiết biến thể',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(blank=True, null=True, verbose_name='Nội dung đánh giá')),
                ('reply', models.TextField(blank=True, null=True, verbose_name='Phản hồi từ cửa hàng')),
                ('rating', models.IntegerField(choices=[(1, '★☆☆☆☆ - Rất tệ'), (2, '★★☆☆☆ - Tệ'), (3, '★★★☆☆ - Bình thường'), (4, '★★★★☆ - Tốt'), (5, '★★★★★ - Xuất sắc')], default=None, verbose_name='Số sao')),
                ('active', models.BooleanField(default=False, verbose_name='Hiển thị')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đánh giá')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='store.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Đánh giá',
                'verbose_name_plural': 'Đánh giá sản phẩm',
            },
        ),
    ]
