# Generated by Django 4.2 on 2026-04-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Họ và tên')),
                ('mobile', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Số điện thoại')),
                ('email', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Email')),
                ('country', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Quốc gia')),
                ('state', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Tỉnh/Thành phố')),
                ('city', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Quận/Huyện')),
                ('address', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Địa chỉ cụ thể')),
                ('zip_code', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Mã bưu chính')),
            ],
            options={
                'verbose_name': 'Địa chỉ',
                'verbose_name_plural': 'Địa chỉ khách hàng',
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('New Order', 'Đơn hàng mới'), ('Item Shipped', 'Hàng đang giao'), ('Item Delivered', 'Đã giao hàng')], default=None, max_length=100, verbose_name='Loại thông báo')),
                ('seen', models.BooleanField(default=False, verbose_name='Đã xem')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày thông báo')),
            ],
            options={
                'verbose_name': 'Thông báo',
                'verbose_name_plural': 'Thông báo khách hàng',
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Yêu thích',
                'verbose_name_plural': 'Danh sách yêu thích',
            },
        ),
    ]
