# Generated by Django 4.2 on 2026-04-05 14:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images', verbose_name='Ảnh bìa')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('slug', models.SlugField(blank=True, max_length=350, unique=True, verbose_name='Đường dẫn')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Nội dung')),
                ('tags', models.CharField(blank=True, max_length=200, null=True, verbose_name='Thẻ tag')),
                ('status', models.CharField(choices=[('Draft', 'Bản nháp'), ('Published', 'Đã đăng')], default='Published', max_length=10, verbose_name='Trạng thái')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Lượt xem')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Bài viết nổi bật')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Ngày đăng')),
            ],
            options={
                'verbose_name': 'Bài viết',
                'verbose_name_plural': 'Bài viết',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên danh mục')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True, verbose_name='Đường dẫn')),
            ],
            options={
                'verbose_name': 'Danh mục',
                'verbose_name_plural': 'Danh mục bài viết',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Họ và tên')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Nội dung bình luận')),
                ('approved', models.BooleanField(default=False, verbose_name='Đã duyệt')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày bình luận')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blog', verbose_name='Bài viết')),
            ],
            options={
                'verbose_name': 'Bình luận',
                'verbose_name_plural': 'Bình luận bài viết',
            },
        ),
    ]
